name: First-time contributor reminder

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  remind:
    uses: git-mastery/actions/.github/workflows/first-time-contributor.yml@main
    secrets: inherit
